config/routes.rb
Dengueapp::Application.routes.draw do

  get "denunciantes/index"

  match "download" => "public#download", :as => "download"
  match "download/android" => "public#download_android", :as => "download_android"
  match "conheca_a_aplicacao" => "public#conheca_a_aplicacao", :as => "conheca_a_aplicacao"
  match "estatisticas" => "public#estatisticas", :as => "estatisticas"

  match "acesso_negado" => "application#acesso_negado", :as => "acesso_negado"
  
  match "webservices/denuncias" => "webservices#denuncias", :as => "webservice_denuncias"
  match "webservices/denuncias/publicar" => "webservices#publicar_denuncia", :as => "webservice_publicar_denuncia", :via => :post
  match "webservices/reportar_excecao" => "webservices#reportar_excecao", :as => "webservice_reportar_excecao", :via => :post
  match "webservices/status_do_servidor" => "webservices#status_do_servidor", :as => "webservice_status_do_servidor", :via => :post
  match "webservices/registro_do_dispositivo" => "webservices#registro_do_dispositivo", :as => "webservice_registro_do_dispositivo"

  match "usuario/:id/cancelar/" => "devise/registrations#cancelar", :as => "cancelar_usuario_registration"
  devise_for :usuarios
  
  match 'operadores/:id/desativar' => 'operadores#desativar', :as => "desativar_operador"
  match 'operadores/:id/ativar' => 'operadores#ativar', :as => "ativar_operador"
  resources :operadores do
    get 'administradores', :on => :collection
    get 'moderadores', :on => :collection
  end

  match 'denuncias/:id/rejeitar' => 'denuncias#rejeitar', :as => "rejeitar_denuncia"
  match 'denuncias/:id/reativar' => 'denuncias#reativar', :as => "reativar_denuncia"
  resources :denuncias do
    get 'update_situacao'
  end

  resources :denunciantes, :only => [:index] do
    get 'banir', :on => :collection
  end

  resources :dispositivos do
    put 'vincular', :on => :collection
  end
  
  authenticated :usuario do
    root :to => 'public#index'
  end
  root :to => 'public#index'

  

end

app/controllers/operadores_controller.rb
#!/bin/env ruby
# encoding: utf-8

class OperadoresController < ApplicationController
  before_filter :authenticate_usuario!
  authorize_resource :class => false
  
  def index
    @operadores = Usuario.operadores
  end

  def new
    @operador = Usuario.new
  end

  def create
    @operador = Usuario.new(params[:usuario])
    @operador.password_confirmation = @operador.password = Usuario::SENHA_PADRAO
    if @operador.save
      DengueAppMailer.notificar_alteracao_em_operador(@operador,"ativado").deliver
      redirect_to operadores_path, :notice => "Operador ##{@operador.id} cadastrado  com sucesso."
    else
      render :action => "new"
    end
  end

  def edit
    @operador = Usuario.find(params[:id])
  end

  def update
    @operador = Usuario.find(params[:id])
      if @operador.update_attributes(params[:usuario])
        redirect_to operadores_path, :notice => "Dados do operador ##{@operador.id} alterados com sucesso."
      else
        render :action => "edit"
      end

  end

end

app/helpers/operadores_helper.rb
#!/bin/env ruby
# encoding: utf-8

module OperadoresHelper

  def badge_de_tipo_ou_situacao(tipo_operador_codificado)
    case tipo_operador_codificado
      when Usuario::MODERADOR
        texto = "Moderador"
        cor_do_badge = "info"
      when Usuario::ADMINISTRADOR
        texto = "Administrador"
        cor_do_badge = "inverse"
      when Usuario::OPERADOR_INATIVO
        texto = "Operador Inativo"
        cor_do_badge = "default"
    end
    "<span class='badge badge-#{cor_do_badge}'>#{texto}</span>".html_safe
  end

end

app/views/operadores/_form.html.erb
<%= render "layouts/error_messages", :target => @operador %>

  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field span6' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field span4' %>
    </div>
  </div>
<div class="control-group">
  <%= f.label :tipo_operador, "Tipo de Operador", :class => 'control-label' %>
  <div class="controls">
    <label class="radio">
      <%= f.radio_button :tipo_operador, Usuario::MODERADOR, :checked => true %>
      <%= f.label :tipo_operador_5, 'Moderador' %>
      <%= f.radio_button :tipo_operador, Usuario::ADMINISTRADOR %>
      <%= f.label :tipo_operador_8, 'Administrador' %>
      <% unless f.object.new_record? %>
          <%= f.radio_button :tipo_operador, Usuario::OPERADOR_INATIVO %>
          <%= f.label :tipo_operador_0, 'Desativado' %>
      <% end %>
    </label>
  </div>
</div>
<div class="form-actions">
  <%= link_to "Cancelar e Voltar", 'javascript:history.back()', :class => 'btn' %>
  <%= f.submit "Salvar", :class => 'btn btn-success' %>
</div>

app/views/operadores/_menu.html.erb
<div class="span2">
  <h4>Opções</h4>
  <hr>
  <ul class="nav nav-list">
    <li class="<%= is_active?(operadores_path) %>">
      <%= link_to "Listar Todos os Operadores", operadores_path %>
    </li>
    <li class="<%= is_active?(new_operador_path) %>">
      <%= link_to "Cadastrar Operador", new_operador_path %>
    </li>
  </ul>
</div>

app/views/operadores/edit.html.erb
<div class="row-fluid">
  <%= render "menu" %>
  <div class="span10">
    <%- model_class = @operador.class -%>
    <h4>Editar Dados do Operador #<%= @operador.id %></h4>
    <hr>
        <%= form_for @operador ,:url => operador_path(@operador), :method => :put ,:html => { :class => 'form-horizontal' } do |f| %>
            <%= render 'form', :f => f %>
        <% end %>
  </div>
</div>

app/views/operadores/index.html.erb
<div class="row-fluid">
  <%= render "menu" %>
  <div class="span10">
    <h4>Gerenciamento de Operadores</h4>
    <hr>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>E-mail</th>
          <th>Tipo/Situação do Operador</th>
          <th>Data de Cadastro</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @operadores.each do |operador| %>
          <tr>
            <td><%= "##{operador.id}" %></td>
            <td><%= operador.nome %></td>
            <td><%= operador.email %></td>
            <td><%= badge_de_tipo_ou_situacao(operador.tipo_operador) %></td>
            <td><%= I18n.l operador.created_at %></td>
            <td>
              <%= link_to "Editar", edit_operador_path(operador), :class => 'btn btn-primary btn-mini'  %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/operadores/new.html.erb
<div class="row-fluid">
  <%= render "menu" %>
  <div class="span10">
    <%- model_class = @operador.class -%>
    <h4>Cadastrar Operador</h4>
    <hr>
    <%= form_for @operador ,:url => operadores_path(@operador), :method => :post ,:html => { :class => 'form-horizontal' } do |f| %>
        <%= render 'form', :f => f %>
    <% end %>
  </div>
</div>