config/routes.rb
Dengueapp::Application.routes.draw do

  get "denunciantes/index"

  match "download" => "public#download", :as => "download"
  match "download/android" => "public#download_android", :as => "download_android"
  match "conheca_a_aplicacao" => "public#conheca_a_aplicacao", :as => "conheca_a_aplicacao"
  match "estatisticas" => "public#estatisticas", :as => "estatisticas"

  match "acesso_negado" => "application#acesso_negado", :as => "acesso_negado"
  
  match "webservices/denuncias" => "webservices#denuncias", :as => "webservice_denuncias"
  match "webservices/denuncias/publicar" => "webservices#publicar_denuncia", :as => "webservice_publicar_denuncia", :via => :post
  match "webservices/reportar_excecao" => "webservices#reportar_excecao", :as => "webservice_reportar_excecao", :via => :post
  match "webservices/status_do_servidor" => "webservices#status_do_servidor", :as => "webservice_status_do_servidor", :via => :post
  match "webservices/registro_do_dispositivo" => "webservices#registro_do_dispositivo", :as => "webservice_registro_do_dispositivo"

  match "usuario/:id/cancelar/" => "devise/registrations#cancelar", :as => "cancelar_usuario_registration"
  devise_for :usuarios
  
  match 'operadores/:id/desativar' => 'operadores#desativar', :as => "desativar_operador"
  match 'operadores/:id/ativar' => 'operadores#ativar', :as => "ativar_operador"
  resources :operadores do
    get 'administradores', :on => :collection
    get 'moderadores', :on => :collection
  end

  match 'denuncias/:id/rejeitar' => 'denuncias#rejeitar', :as => "rejeitar_denuncia"
  match 'denuncias/:id/reativar' => 'denuncias#reativar', :as => "reativar_denuncia"
  resources :denuncias do
    get 'update_situacao'
  end

  resources :denunciantes, :only => [:index] do
    get 'banir', :on => :collection
  end

  resources :dispositivos do
    put 'vincular', :on => :collection
  end
  
  authenticated :usuario do
    root :to => 'public#index'
  end
  root :to => 'public#index'

  

end

app/models/denunciante.rb
#!/bin/env ruby
# encoding: utf-8

class Denunciante < ActiveRecord::Base

  CADASTRADO = "UDSC"
  BANIDO = "UDSB"
  DESISTENTE = "UDSD"
  
  belongs_to :usuario
  has_many :denuncias
  has_many :dispositivos
  
  accepts_nested_attributes_for :usuario
  
  before_create :atribuir_valores_iniciais
  
  def atribuir_valores_iniciais
    self.situacao = Denunciante::CADASTRADO if self.situacao.blank?
  end
  
  def banivel?
    if (self.denuncias.rejeitadas.count >= 3) and (self.situacao == Denunciante::CADASTRADO)
      return true
    else
      return false
    end
  end
  
  def banir
    if self.banivel?
      #TODO: Colocar num transaction a alteração de status do usuários e suas denuncias ativas
      self.update_attribute(:situacao,Denunciante::BANIDO)
      self.denuncias.ativas.each do |d|
        d.rejeitar
      end
    else
      errors[:base] << "Somente usuários com situação CADASTRADO e pelo menos 3 denúncias rejeitadas podem ser banidos."
    end
  end
  
  def desistir
    if self.situacao == Denunciante::CADASTRADO
      #TODO: Colocar num transaction a alteração de status do usuários e suas denuncias ativas
      self.update_attribute(:situacao,Denunciante::DESISTENTE)
      self.denuncias.ativas.each do |d|
        d.cancelar
      end
    else
      errors[:base] << "Somente usuários com situação CADASTRADO podem ser alterados para DESISTENTE."
    end
  end
  
end

app/controllers/denunciantes_controller.rb
#!/bin/env ruby
# encoding: utf-8

class DenunciantesController < ApplicationController
  before_filter :authenticate_usuario!
  authorize_resource :class => false

  def index
    @denunciantes = Dispositivo.all(:include => :usuario)
    if !params[:usuario_id].blank?
      @denunciantes = @denunciantes.where(:usuario_id => params[:usuario_id])
    end
    if !params[:dispositivo_id].blank?
      @denunciantes = @denunciantes.where(:id => params[:dispositivo_id])
    end
    if params[:apenas_baniveis] == "true"
      denunciantes_temp = @denunciantes
      @denunciantes = []
      denunciantes_temp.each do |d|
        @denunciantes << d if (d.banivel? or (d.usuario and d.banivel?))
      end
    end
  end

  def banir
    if params[:dispositivo_id]
      dispositivo = Dispositivo.find(params[:dispositivo_id])
      unless dispositivo.banir
        erro = dispositivo.errors.full_messages
      end
    elsif params[:usuario_id]
      usuario = Usuario.find(params[:usuario_id])
      unless usuario.banir
        erro = usuario.errors.full_messages
      end
    end
    if erro.blank?
      redirect_to :back, :notice => "Denunciante banido com sucesso"
    else
      redirect_to :back, :alert => erro
    end
  end

end

app/helpers/denunciantes_helper.rb
module DenunciantesHelper

  def badge_de_situacao_de_dispositivo(situacao_codificada)
    case situacao_codificada
      when Dispositivo::CADASTRADO
        texto = "Cadastrado"
        cor_do_badge = "info"
      when Dispositivo::BANIDO
        texto = "Banido"
        cor_do_badge = "important"
      else
        texto = "Desconhecido"
        cor_do_badge = "default"
    end
    "<span class='badge badge-#{cor_do_badge}'>#{texto}</span>".html_safe
  end

  def badge_de_situacao_de_usuario(situacao_codificada)
    case situacao_codificada
      when Usuario::DENUNCIANTE_CADASTRADO
        texto = "Cadastrado"
        cor_do_badge = "info"
      when Usuario::DENUNCIANTE_BANIDO
        texto = "Banido"
        cor_do_badge = "important"
      when Usuario::DENUNCIANTE_DESISTENTE
        texto = "Desistente"
        cor_do_badge = "default"
      else
        texto = "Desconhecido"
        cor_do_badge = "default"
    end
    "<span class='badge badge-#{cor_do_badge}'>#{texto}</span>".html_safe
  end

end

app/views/denunciantes/_menu.html.erb
<div class="span2">

    <h4>Pesquisar</h4>
    <hr>
    <%= form_tag(denunciantes_path, :method => "get") do %>

          <%= label_tag(:apenas_baniveis, "Mostrar Apenas Baníveis") %>
          <%= check_box_tag(:apenas_baniveis, true, params[:apenas_baniveis]) %><br /><br/>

          <%= label_tag(:usuario_id, "ID do Usuário") %>
          <div class="input-prepend">
            <span class="add-on">#</span>
            <%= text_field_tag :usuario_id, params[:usuario_id], :class => "input-mini" %>
          </div>

          <%= label_tag(:dispositivo_id, "ID do Dispositivo") %>
          <div class="input-prepend">
            <span class="add-on">#</span>
            <%= text_field_tag :dispositivo_id, params[:dispositivo_id], :class => "input-mini" %>
          </div>

          <br /><%= submit_tag "Pesquisar", :class => 'btn btn-primary' %>
    <% end %>

</div>

app/views/denunciantes/index.html.erb
<div class="row-fluid">
  <%= render "menu" %>
  <div class="span10">
    <h4>Gerenciar Denunciantes</h4>
    <hr>
    <div class="row-fluid">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th colspan="3" style="text-align: center;">Dados do Dispositivo</th>
          <th colspan="3" style="text-align: center;">Dados do Denunciante</th>
          <th rowspan="2" style="text-align: center; vertical-align: middle;">Observações</th>
          <th rowspan="2" style="text-align: center; vertical-align: middle;">Ações</th>
        </tr>
        <tr>
          <th style="text-align: center;">ID</th>
          <th style="text-align: center;">Data de Cadastro</th>
          <th style="text-align: center;">Situação</th>
          <th style="text-align: center;">ID</th>
          <th style="text-align: center;">Data de Cadastro</th>
          <th style="text-align: center;">Situação</th>
        </tr>
        </thead>
        <tbody>
        <% @denunciantes.each do |d| %>
            <tr>
              <td><%= "##{d.id}" %></td>
              <td style="text-align: center;"><%=I18n.l d.created_at %></td>
              <td style="text-align: center;"><%= badge_de_situacao_de_dispositivo(d.situacao) %></td>
              <% if d.usuario %>
              <td style="text-align: center;"><%= "##{d.usuario_id}" %></td>
              <td style="text-align: center;"><%= I18n.l d.usuario.created_at %></td>
              <td style="text-align: center;"><%= badge_de_situacao_de_usuario(d.usuario.denunciante_situacao) %></td>
              <% else %>
                <td colspan="3" style="text-align: center;">Não há usuário vinculado</td>
              <% end %>
              <td style="text-align: center;">
                <% if d.banivel? or (d.usuario and d.usuario.banivel?) %>
                    <span class='badge badge-warning'>Banível</span>
                <% else %>
                    &nbsp;
                <% end %>
              </td>
              <td style="text-align: right;">
                <% if d.usuario %>
                    <%= link_to "Banir Usuário", banir_denunciantes_path(:usuario_id => d.usuario), :class => 'btn btn-danger btn-mini' if d.usuario.banivel? %>
                    <%= link_to "Ver Denúncias do Usuário", denuncias_path(:usuario_id => d.usuario_id), :class => 'btn btn-mini btn-primary' %>
              <% else %>
                    <%= link_to "Banir Dispositivo", banir_denunciantes_path(:dispositivo_id => d), :class => 'btn btn-danger btn-mini' if d.banivel? %>
                    <%= link_to "Ver Denúncias do Dispositivo", denuncias_path(:dispositivo_id => d.id), :class => 'btn btn-mini btn-primary' %>
              <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>
</div>