config/routes.rb
Dengueapp::Application.routes.draw do

  get "denunciantes/index"

  match "download" => "public#download", :as => "download"
  match "download/android" => "public#download_android", :as => "download_android"
  match "conheca_a_aplicacao" => "public#conheca_a_aplicacao", :as => "conheca_a_aplicacao"
  match "estatisticas" => "public#estatisticas", :as => "estatisticas"

  match "acesso_negado" => "application#acesso_negado", :as => "acesso_negado"
  
  match "webservices/denuncias" => "webservices#denuncias", :as => "webservice_denuncias"
  match "webservices/denuncias/publicar" => "webservices#publicar_denuncia", :as => "webservice_publicar_denuncia", :via => :post
  match "webservices/reportar_excecao" => "webservices#reportar_excecao", :as => "webservice_reportar_excecao", :via => :post
  match "webservices/status_do_servidor" => "webservices#status_do_servidor", :as => "webservice_status_do_servidor", :via => :post
  match "webservices/registro_do_dispositivo" => "webservices#registro_do_dispositivo", :as => "webservice_registro_do_dispositivo"

  match "usuario/:id/cancelar/" => "devise/registrations#cancelar", :as => "cancelar_usuario_registration"
  devise_for :usuarios
  
  match 'operadores/:id/desativar' => 'operadores#desativar', :as => "desativar_operador"
  match 'operadores/:id/ativar' => 'operadores#ativar', :as => "ativar_operador"
  resources :operadores do
    get 'administradores', :on => :collection
    get 'moderadores', :on => :collection
  end

  match 'denuncias/:id/rejeitar' => 'denuncias#rejeitar', :as => "rejeitar_denuncia"
  match 'denuncias/:id/reativar' => 'denuncias#reativar', :as => "reativar_denuncia"
  resources :denuncias do
    get 'update_situacao'
  end

  resources :denunciantes, :only => [:index] do
    get 'banir', :on => :collection
  end

  resources :dispositivos do
    put 'vincular', :on => :collection
  end
  
  authenticated :usuario do
    root :to => 'public#index'
  end
  root :to => 'public#index'

  

end

app/models/denuncia.rb
#!/bin/env ruby
# encoding: utf-8

class Denuncia < ActiveRecord::Base
  
  ATIVA = "DNSA"
  REJEITADA = "DNSR"
  CANCELADA = "DNSC"
  RESOLVIDA = "DNSS"

  QTD_DENUNCIAS_REJEITADAS_PARA_BANIR_DENUNCIANTE = 3
  
  belongs_to :dispositivo
  has_attached_file :foto,
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :dropbox_options => {
      :path => proc { "foto_denuncia_#{Rails.env}_#{id}.jpg" }
    }
  accepts_nested_attributes_for :dispositivo
  
  acts_as_gmappable :process_geocoding => false

  before_save :identificar_bairro_e_cidade
  before_create :atribuir_valores_iniciais
  after_save :atualizar_banilidade_do_usuario_ou_dispositivo
  
  scope :ativas, where(:situacao => Denuncia::ATIVA)
  scope :rejeitadas, where(:situacao => Denuncia::REJEITADA)
  scope :canceladas, where(:situacao => Denuncia::CANCELADA)
  scope :resolvidas, where(:situacao => Denuncia::RESOLVIDA)
  scope :do_denunciante, lambda{ |denunciante_id| where(:denunciante_id => denunciante_id) unless denunciante_id.blank? }

  def self.do_usuario(usuario_id)
    Denuncia.joins(:dispositivo).where(:dispositivos => {:usuario_id => usuario_id})
  end

  def gmaps4rails
    "#{self.latitude},#{self.longitude}"
  end
  
  def atribuir_valores_iniciais
    self.situacao = Denuncia::ATIVA if self.situacao.blank?
    self.data_e_hora = Time.now if self.data_e_hora.blank?
  end
  
  def ativa?
    return true if self.situacao == Denuncia::ATIVA
  end
  
  def reativavel?
    return true if self.rejeitada?
  end
  
  def reativar
    if self.reativavel?
      self.update_attribute(:situacao,Denuncia::ATIVA)
    else
      errors[:base] << "Somente denúncias com situação REJEITADA, CANCELADA ou RESOLVIDA podem ser reativadas."
    end
  end
  
  def rejeitada?
    return true if self.situacao == Denuncia::REJEITADA
  end
  
  def rejeitavel?
    if self.situacao == Denuncia::ATIVA
      return true
    else
      return false
    end
  end
  
  def rejeitar
    if self.situacao == Denuncia::ATIVA
      self.update_attribute(:situacao,Denuncia::REJEITADA)
    else
      errors[:base] << "Somente denúncias com situação ATIVA podem ser rejeitadas."
    end
  end
  
  def cancelada?
    return true if self.situacao == Denuncia::CANCELADA
  end
  
  def cancelar
    if self.situacao == Denuncia::ATIVA
      self.update_attribute(:situacao,Denuncia::CANCELADA)
    else
      errors[:base] << "Somente denúncias com situação ATIVA podem ser canceladas."
    end
  end
  
  def resolvida?
    return true if self.situacao == Denuncia::RESOLVIDA
  end
  
  def resolver
    if self.situacao == Denuncia::ATIVA
      self.update_attribute(:situacao,Denuncia::RESOLVIDA)
    else
      errors[:base] << "Somente denúncias com situação ATIVA podem ser resolvidas."
    end
  end

  private

  def identificar_bairro_e_cidade
    if (self.new_record? or self.changes.include? "latitude" or self.changes.include? "longitude")
      endereco_geocodificado = Gmaps4rails.geocode("#{self.latitude},#{self.longitude}").first
      endereco_geocodificado[:full_data]["address_components"].each do |c|
        self.bairro = c["long_name"] if c["types"].include? "sublocality"
        self.cidade = c["long_name"] if c["types"].include? "locality"
      end
    end
  end

  def atualizar_banilidade_do_usuario_ou_dispositivo
    if self.changes.include? "situacao" and self.situacao == REJEITADA
      if self.dispositivo.usuario_id
        qtd_denuncias_rejeitadas = Denuncia.do_usuario(self.dispositivo.usuario_id).where(:situacao => REJEITADA).count
        if qtd_denuncias_rejeitadas >= QTD_DENUNCIAS_REJEITADAS_PARA_BANIR_DENUNCIANTE
          self.dispositivo.usuario.update_attribute(:banivel,true)
        end
      else
        qtd_denuncias_rejeitadas = self.dispositivo.denuncias.where(:situacao => REJEITADA).count
        if qtd_denuncias_rejeitadas >= QTD_DENUNCIAS_REJEITADAS_PARA_BANIR_DENUNCIANTE
          self.dispositivo.update_attribute(:banivel,true)
        end
      end
    end
  end

end

app/controllers/denuncias_controller.rb
#!/bin/env ruby
# encoding: utf-8

class DenunciasController < ApplicationController
  before_filter :authenticate_usuario!
  load_and_authorize_resource

  def index
    @denuncias = Denuncia.accessible_by(current_ability,:update_situacao)
    if !params[:situacao].blank?
      @denuncias = @denuncias.where(:situacao => params[:situacao])
    end
    if !params[:usuario_id].blank?
      @denuncias = @denuncias.do_usuario(params[:usuario_id])
    end
    if !params[:dispositivo_id].blank?
      @denuncias = @denuncias.where(:dispositivo_id => params[:dispositivo_id])
    end
    if !params[:denuncia_id].blank?
      @denuncias = @denuncias.where(:id => params[:denuncia_id])
    end
    @denuncias_objeto = @denuncias
    @denuncias = @denuncias.to_gmaps4rails do |denuncia,marker|
      marker.infowindow render_to_string(:partial => 'info_window', :locals => {:denuncia => denuncia})
    end
  end

  def update_situacao
    @denuncia = Denuncia.find(params[:denuncia_id])
    if ((params[:situacao] == Denuncia::ATIVA and current_ability.can? :ativar, @denuncia) or
        (params[:situacao] == Denuncia::REJEITADA and current_ability.can? :rejeitar, @denuncia) or
        (params[:situacao] == Denuncia::CANCELADA and current_ability.can? :cancelar, @denuncia) or
        (params[:situacao] == Denuncia::RESOLVIDA and current_ability.can? :resolver, @denuncia)
    )
      if @denuncia and @denuncia.update_attribute(:situacao,params[:situacao])
        msg_de_erro = ""
      else
        msg_de_erro = "Erro desconhecido ao atualizar a situação da denúncia ##{params[:denuncia_id]}."
      end
    else
      msg_de_erro = "Você não possui permissão para mudar a situação da denúncia ##{params[:denuncia_id]} para a situação desejada."
    end
    if msg_de_erro.empty?
      redirect_to :back, :notice => "Situação da denúncia ##{params[:denuncia_id]} alterada com sucesso."
    else
      redirect_to :back, :alert => msg_de_erro
    end
  end

end

app/helpers/denuncias_helper.rb
#!/bin/env ruby
# encoding: utf-8

module DenunciasHelper

  def badge_de_situacao(situacao_codificada)
    case situacao_codificada
      when Denuncia::ATIVA
        texto_da_situacao = "Ativa"
        cor_do_badge = "info"
      when Denuncia::REJEITADA
        texto_da_situacao = "Rejeitada"
        cor_do_badge = "important"
      when Denuncia::CANCELADA
        texto_da_situacao = "Cancelada"
        cor_do_badge = "inverse"
      when Denuncia::RESOLVIDA
        texto_da_situacao = "Resolvida"
        cor_do_badge = "success"
    end
    "<span class='badge badge-#{cor_do_badge}' style='float: right;'>#{texto_da_situacao}</span>".html_safe
  end
  
end

app/views/denuncias/_info_window.erb
<div class="thumbnail" style="background: none;">
  <div style="cursor: url(/icone_lupa.gif),auto">
    <a style="cursor: url(/icone_lupa.gif),auto" href=<%="#myModal#{denuncia.id}"%> data-toggle="modal" ><%= image_tag denuncia.foto.url, {:style => "width: 240px"} %></a>
  </div>
  <div class="caption">
    <h4>
      Denúncia #<%= denuncia.id %>
      <%= badge_de_situacao(denuncia.situacao) %>
    </h4>
    <p style="color: black;">Enviada em <%= I18n.l denuncia.data_e_hora %></p>
        <p>
          <% if current_user and (current_user.administrador? or current_user.moderador?) %>
             <% dispositivo_id = denuncia.dispositivo_id if denuncia.dispositivo.usuario_id.blank? %>
            <%= link_to "Ver denúncias deste denunciante", denuncias_path(:dispositivo_id => dispositivo_id, :usuario_id => denuncia.dispositivo.usuario_id), :class => "btn btn-mini btn-inverse" %>
          <% end %>
          <% if current_ability.can? :ativar, denuncia %>
            <%= link_to "Reativar", denuncia_update_situacao_path(denuncia, :situacao => Denuncia::ATIVA), :class => "btn btn-mini btn-success" %>
          <% end %>
          <% if current_ability.can? :rejeitar, denuncia %>
            <%= link_to "Rejeitar", denuncia_update_situacao_path(denuncia, :situacao => Denuncia::REJEITADA), :class => "btn btn-mini btn-danger" %>
          <% end %>
          <% if current_ability.can? :cancelar, denuncia %>
              <%= link_to "Cancelar", denuncia_update_situacao_path(denuncia, :situacao => Denuncia::CANCELADA), :class => "btn btn-mini btn-warning" %>
          <% end %>
          <% if current_ability.can? :resolver, denuncia %>
            <%= link_to "Resolver", denuncia_update_situacao_path(denuncia, :situacao => Denuncia::RESOLVIDA), :class => "btn btn-mini btn-success" %>
          <% end %>
        </p>
  </div>
</div>

app/views/denuncias/_mapa_fill_screen.html.erb
<div id="mapa_fill_screen" class="fill_screen">
  <script type="text/javascript">
      var divHeight = document.documentElement.clientHeight;
      document.getElementById('mapa_fill_screen').style.height = (divHeight-100+29)+"px";
  </script>
  <%= gmaps("map_options" => {
            :center_latitude => "-22.890209",
            :center_longitude => "-43.296562",
            :type => "HYBRID",
            :zoom => 11,
            :auto_adjust => false
            },
            :markers => {"data" => denuncias}
      ) %>
</div>

<% denuncias_objeto.each do |d| %>
    <%= render :partial => "denuncias/modal", :locals => {:d => d} %>
<% end %>

app/views/denuncias/_menu.html.erb
<div class="span2">

    <h4>Pesquisar</h4>
    <hr>
    <%= form_tag(denuncias_path, :method => "get") do %>
        <%= label_tag :situacao, "Situação" %>
        <%= select_tag(:situacao,options_for_select([
                 ['Ativas',Denuncia::ATIVA],
                 ['Rejeitadas',Denuncia::REJEITADA],
                 ['Canceladas',Denuncia::CANCELADA],
                 ['Resolvidas', Denuncia::RESOLVIDA]],
                    :selected => params[:situacao]),
            :include_blank => true) %>

      <% if usuario_atual.moderador? or usuario_atual.administrador? %>
          <%= label_tag(:usuario_id, "ID do Usuário") %>
          <div class="input-prepend">
            <span class="add-on">#</span>
            <%= text_field_tag :usuario_id, params[:usuario_id], :class => "input-mini" %>
          </div>

          <%= label_tag(:dispositivo_id, "ID do Dispositivo") %>
          <div class="input-prepend">
            <span class="add-on">#</span>
            <%= text_field_tag :dispositivo_id, params[:dispositivo_id], :class => "input-mini" %>
          </div>

          <%= label_tag(:denuncia_id, "ID da Denúncia") %>
          <div class="input-prepend">
            <span class="add-on">#</span>
            <%= text_field_tag :denuncia_id, params[:denuncia_id], :class => "input-mini" %>
          </div>
       <% else %>
            <% hidden_field_tag :usuario_id, params[:usuario_id] %>
       <% end %>
          <br /><%= submit_tag "Pesquisar", :class => 'btn btn-primary' %>
    <% end %>

</div>

app/views/denuncias/_modal.html.erb
<div id=<%= "myModal#{d.id}" %> class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby=<%= "myModalLabel#{d.id}" %> aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <p id="myModalLabel" style="font-style: italic;">Foto da Denúncia #<%= d.id%></p>
  </div>
  <div class="modal-body">
    <%= image_tag d.foto.url, {:width => "540px"} %>
  </div>
</div>

app/views/denuncias/estatisticas.html.erb
<div class="row-fluid">
  <div class="span4">
    <h3>Denúncias por bairro</h3>
    <table>
      <thead>
        <tr>
          <th>Bairro</th>
          <th>Quantidade</th>
        </tr>
      </thead>
      <tbody>
        <% @denuncias_por_bairro.each do |b| %>
        <tr>
          <td><%= b[0] %></td>
          <td><%= b[1] %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="span4">
    <h3>Denúncias por cidade</h3>
    <table>
      <thead>
      <tr>
        <th>Cidade</th>
        <th>Quantidade</th>
      </tr>
      </thead>
      <tbody>
      <% @denuncias_por_cidade.each do |c| %>
          <tr>
            <td><%= c[0] %></td>
            <td><%= c[1] %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="span4">
    <h3>Quantidade de denúncias recebidas por dia</h3>
  </div>
</div>

app/views/denuncias/index.html.erb
<div class="row-fluid">
  <%= render "menu" %>
  <div class="span10" style="height:600px">
    <%= render "mapa_fill_screen", :denuncias => @denuncias, :denuncias_objeto => @denuncias_objeto %>
  </div>
</div>