config/routes.rb
Dengueapp::Application.routes.draw do

  get "denunciantes/index"

  match "download" => "public#download", :as => "download"
  match "download/android" => "public#download_android", :as => "download_android"
  match "conheca_a_aplicacao" => "public#conheca_a_aplicacao", :as => "conheca_a_aplicacao"
  match "estatisticas" => "public#estatisticas", :as => "estatisticas"

  match "acesso_negado" => "application#acesso_negado", :as => "acesso_negado"
  
  match "webservices/denuncias" => "webservices#denuncias", :as => "webservice_denuncias"
  match "webservices/denuncias/publicar" => "webservices#publicar_denuncia", :as => "webservice_publicar_denuncia", :via => :post
  match "webservices/reportar_excecao" => "webservices#reportar_excecao", :as => "webservice_reportar_excecao", :via => :post
  match "webservices/status_do_servidor" => "webservices#status_do_servidor", :as => "webservice_status_do_servidor", :via => :post
  match "webservices/registro_do_dispositivo" => "webservices#registro_do_dispositivo", :as => "webservice_registro_do_dispositivo"

  match "usuario/:id/cancelar/" => "devise/registrations#cancelar", :as => "cancelar_usuario_registration"
  devise_for :usuarios
  
  match 'operadores/:id/desativar' => 'operadores#desativar', :as => "desativar_operador"
  match 'operadores/:id/ativar' => 'operadores#ativar', :as => "ativar_operador"
  resources :operadores do
    get 'administradores', :on => :collection
    get 'moderadores', :on => :collection
  end

  match 'denuncias/:id/rejeitar' => 'denuncias#rejeitar', :as => "rejeitar_denuncia"
  match 'denuncias/:id/reativar' => 'denuncias#reativar', :as => "reativar_denuncia"
  resources :denuncias do
    get 'update_situacao'
  end

  resources :denunciantes, :only => [:index] do
    get 'banir', :on => :collection
  end

  resources :dispositivos do
    put 'vincular', :on => :collection
  end
  
  authenticated :usuario do
    root :to => 'public#index'
  end
  root :to => 'public#index'

  

end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
      <div class="container-fluid">
      <!-- LINKS -->
      <%= link_to "DengueApp", root_path, :class => "brand" %>
      <div class="nav-collapse collapse" style="height: 0px;">
      <ul class="nav" role="navigation">
        <!-- DROPDOWN DENUNCIAS -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Denúncias<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li><%= link_to "Denúncias dos Usuários", root_path %></li>
            <% if usuario_atual and usuario_atual.denunciante? %>
                <li><%= (link_to "Minhas Denúncias", denuncias_path(:usuario_id => usuario_atual.id)) %></li>
            <% end %>
            <li><%= link_to "Estatísticas", estatisticas_path %></li>
          </ul>
        </li>
        <!-- DROPDOWN DENUNCIAS -> DROPDOWN FUNCOES ADMINISTRATIVAS -->
        <% if usuario_atual and (usuario_atual.administrador? or usuario_atual.moderador?) %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Funções Administrativas<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li><%= (link_to "Gerenciar Denuncias", denuncias_path) if can? :update_situacao, Denuncia %></li>
            <li><%= (link_to "Gerenciar Denunciantes", denunciantes_path) if can? :index, :denunciante %></li>
            <li><%= (link_to "Gerenciar Operadores", operadores_path) if can? :manage, :operador %></li>
          </ul>
        </li>
        <% end %>
        <!-- DROPDOWN FUNCOES ADMINISTRAIVAS -> DOWNLOAD ANDROID -->
        <li><%= link_to("Download do Aplicativo Android", download_path) %></li>
        <!-- DOWNLOAD ADNROID -> DROPDOW AJUDA -->
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Ajuda<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li><%= link_to "Sobre a Aplicação", conheca_a_aplicacao_path %></li>
            <li><%= link_to "Contato", "https://docs.google.com/spreadsheet/viewform?fromEmail=true&formkey=dGloOVpIUThNN0tWWkhwZWNJQkl3ekE6MQ" %></li>
          </ul>
        </li>
      </ul>
      <!-- DROPDOWN AJUDA -> DROPDOWN CONTA USUARIO/LOGIN -->
      <ul class="nav pull-right">
        <% if usuario_atual %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= usuario_atual.email %><b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li><%= (link_to "Meus Dispositivos", dispositivos_path if current_user.denunciante?)%></li>
                <li><%= (link_to "Minha Conta de Usuário", edit_usuario_registration_path) %></li>
                <li><%= link_to('Sair', destroy_usuario_session_path, :method => :delete) %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to('Acompanhar Minhas Denúncias', new_usuario_session_path)%></li>
        <% end %>
      </ul>
      <!-- FIM MENUS/LINKS-->
      </div>
    </div>
      
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DengueApp</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag 'gmaps4rails' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
      
      <%= render "layouts/navbar" %>
      <div class="container-fluid">
      <!-- MENSAGENS FLASH -->
      
      <% flash.each do |type, message| -%>
        <% type = "info" if type == :notice %>
        <% type = "error" if type == :alert %>
        <div class="alert alert-<%= type %>">
          <a class="close" data-dismiss="alert" href="#">x</a>
          <%= message %>
        </div>
      <% end %>
      <!-- CONTEUDO DA PAGINA -->
      
      <%= yield %>

      </div>
      
  <%= yield :scripts %>
</body>
</html>

app/views/layouts/dengue_app_mailer.text.erb
Olá, <%= exibir_primeiro_nome(@usuario.nome) %>!

<%= yield %>

DengueApp
dengue.herokuapp.com

--
Este é um e-mail gerado automaticamente pelo sistema e não deve ser respondido.
Caso queira entrar em contato, vá em dengue.herokuapp.com e no menu superior escolha "Ajuda" e então "Contato".